"""
Offline Training Module

Implements:
- Historical data extraction and preprocessing
- Offline pre-training using Conservative Q-Learning (CQL)
- Action inference from historical state changes
- Validation and evaluation pipelines

===== STEP 1: P-MODEL TRAINING =====
Data Flow: CSV/DB -> OfflineDataExtractor -> Transitions -> OfflineTrainer -> SAC checkpoint
"""

# QA/Testing: Set True to enable input/output logging for traceability
_QA_IO_LOGGING = True

import numpy as np
import torch
from typing import Dict, Any, List, Optional, Tuple
from dataclasses import dataclass
from datetime import datetime, timedelta
import logging
from pathlib import Path
import json
from tqdm import tqdm

from .config import DRLConfig, TrainingConfig, OptimizationGoal, FeatureConfig
from .sac_agent import SACAgent
from .replay_buffer import PrioritizedReplayBuffer, Transition, create_replay_buffer
from .reward_functions import RewardComputer, RewardConfig
from .state_action import CampaignState

logger = logging.getLogger(__name__)


@dataclass
class HistoricalCampaignData:
    """Container for historical campaign data"""
    campaign_id: str
    organization_id: str
    platform: str
    optimization_goal: str
    daily_metrics: List[Dict[str, Any]]  # List of daily snapshots
    actions_taken: List[Dict[str, Any]]  # List of manual actions
    constraints: Dict[str, float]  # Campaign constraints


class OfflineDataExtractor:
    """
    [OfflineDataExtractor]
    Description: Extracts and preprocesses historical campaign data from CSV or DB for offline training.
    Input: metrics_path (CSV), actions_path (optional CSV), or db_session.
    Output: List[HistoricalCampaignData] -> consumed by build_transitions().
    """
    
    def __init__(
        self,
        feature_config: Optional[FeatureConfig] = None,
        normalization_params: Optional[Dict[str, Tuple[float, float]]] = None
    ):
        """
        Args:
            feature_config: Configuration for feature engineering
            normalization_params: Pre-computed (mean, std) for each feature
        """
        self.feature_config = feature_config or FeatureConfig()
        self.normalization_params = normalization_params or {}
    
    async def extract_from_database(
        self,
        db_session: Any,
        lookback_days: int = 90,
        min_campaign_spend: float = 1000,
        min_daily_records: int = 7
    ) -> List[HistoricalCampaignData]:
        """
        Extract historical campaign data from database
        
        Args:
            db_session: Database session
            lookback_days: Days of history to extract
            min_campaign_spend: Minimum spend to include campaign
            min_daily_records: Minimum daily records required
            
        Returns:
            List of HistoricalCampaignData
        """
        # This would query your actual database
        # Placeholder implementation
        logger.info(f"Extracting campaigns from last {lookback_days} days")
        
        # Example query structure (pseudo-code)
        """
        SELECT c.*, m.* FROM campaigns c
        JOIN campaign_metrics m ON c.id = m.campaign_id
        WHERE c.total_spend >= min_campaign_spend
        AND c.created_at >= NOW() - INTERVAL '{lookback_days} days'
        AND c.status IN ('active', 'completed')
        GROUP BY c.id
        HAVING COUNT(DISTINCT m.date) >= min_daily_records
        ORDER BY c.created_at
        """
        
        campaigns = []
        # Implementation would iterate over query results
        return campaigns
    
    def extract_from_csv(
        self,
        metrics_path: str,
        actions_path: Optional[str] = None
    ) -> List[HistoricalCampaignData]:
        """
        [extract_from_csv]
        Description: Loads campaign metrics and optional action logs from CSV files.
        Input: metrics_path (original file), actions_path (optional, generated by previous steps or manual).
        Output: List[HistoricalCampaignData] -> used by build_transitions().
        """
        import pandas as pd
        
        # ----- INPUT LOGGING -----
        if _QA_IO_LOGGING:
            logger.info(f"[IO] INPUT: metrics_path={metrics_path} | actions_path={actions_path or 'None'}")
        logger.info(f"Loading metrics from {metrics_path}")
        metrics_df = pd.read_csv(metrics_path)
        
        actions_df = None
        if actions_path:
            logger.info(f"Loading actions from {actions_path}")
            actions_df = pd.read_csv(actions_path)
        
        campaigns = []
        
        for campaign_id in metrics_df["campaign_id"].unique():
            campaign_metrics = metrics_df[
                metrics_df["campaign_id"] == campaign_id
            ].sort_values("date")
            
            if len(campaign_metrics) < 7:
                continue
            
            daily_metrics = campaign_metrics.to_dict("records")
            
            actions_taken = []
            if actions_df is not None:
                campaign_actions = actions_df[
                    actions_df["campaign_id"] == campaign_id
                ]
                actions_taken = campaign_actions.to_dict("records")
            
            campaigns.append(HistoricalCampaignData(
                campaign_id=str(campaign_id),
                organization_id=str(campaign_metrics.iloc[0].get("organization_id", "")),
                platform=campaign_metrics.iloc[0].get("platform", "unknown"),
                optimization_goal=campaign_metrics.iloc[0].get("optimization_goal", "roas"),
                daily_metrics=daily_metrics,
                actions_taken=actions_taken,
                constraints={
                    "target_cpa": campaign_metrics.iloc[0].get("target_cpa", 50),
                    "min_roas": campaign_metrics.iloc[0].get("min_roas", 1.5),
                    "max_daily_spend": campaign_metrics.iloc[0].get("daily_budget", 1000),
                }
            ))
        
        # ----- OUTPUT LOGGING -----
        if _QA_IO_LOGGING:
            logger.info(f"[IO] OUTPUT: {len(campaigns)} campaigns extracted | Sample campaign_ids: {[c.campaign_id for c in campaigns[:3]]}")
            if campaigns:
                sample = campaigns[0]
                logger.info(f"[IO] Sample row: campaign_id={sample.campaign_id}, platform={sample.platform}, metrics_days={len(sample.daily_metrics)}")
        logger.info(f"Extracted {len(campaigns)} campaigns")
        return campaigns
    
    def build_transitions(
        self,
        campaigns: List[HistoricalCampaignData],
        reward_computer: RewardComputer
    ) -> List[Transition]:
        """
        [build_transitions]
        Description: Converts historical campaign data into (s,a,r,s') transition tuples.
        Input: campaigns (from extract_from_csv/extract_from_database), reward_computer (from RewardComputer).
        Output: List[Transition] -> consumed by OfflineTrainer.load_transitions().
        """
        # ----- INPUT LOGGING -----
        if _QA_IO_LOGGING:
            logger.info(f"[IO] INPUT: {len(campaigns)} campaigns | reward_computer={type(reward_computer).__name__}")
            if campaigns:
                logger.info(f"[IO] Sample campaign: {campaigns[0].campaign_id}, {len(campaigns[0].daily_metrics)} daily records")
        transitions = []
        
        for campaign in tqdm(campaigns, desc="Building transitions"):
            campaign_transitions = self._build_campaign_transitions(
                campaign, reward_computer
            )
            transitions.extend(campaign_transitions)
        
        # ----- OUTPUT LOGGING -----
        if _QA_IO_LOGGING:
            logger.info(f"[IO] OUTPUT: {len(transitions)} transitions | Next: OfflineTrainer.load_transitions()")
            if transitions:
                t = transitions[0]
                logger.info(f"[IO] Sample transition: state_dim={t.state.shape}, reward={t.reward:.4f}, done={t.done}")
        logger.info(f"Built {len(transitions)} transitions from {len(campaigns)} campaigns")
        return transitions
    
    def _build_campaign_transitions(
        self,
        campaign: HistoricalCampaignData,
        reward_computer: RewardComputer
    ) -> List[Transition]:
        """Build transitions for a single campaign"""
        transitions = []
        metrics = campaign.daily_metrics
        
        if len(metrics) < 2:
            return transitions
        
        # Build action lookup from logged actions
        action_lookup = {}
        for action in campaign.actions_taken:
            action_date = action.get("date", action.get("timestamp", ""))[:10]
            action_lookup[action_date] = action
        
        # Create transitions for consecutive days
        for i in range(len(metrics) - 1):
            metrics_t = metrics[i]
            metrics_t1 = metrics[i + 1]
            
            # Extract state at time t
            state_t = self._extract_state(campaign, metrics[:i+1])
            
            # Extract state at time t+1
            state_t1 = self._extract_state(campaign, metrics[:i+2])
            
            # Infer or lookup action
            action_date = metrics_t.get("date", "")[:10]
            if action_date in action_lookup:
                action = self._extract_action_from_log(action_lookup[action_date])
            else:
                action = self._infer_action(metrics_t, metrics_t1)
            
            # Compute reward
            goal = OptimizationGoal(campaign.optimization_goal)
            reward_obj = reward_computer.compute(
                metrics_before=metrics_t,
                metrics_after=metrics_t1,
                action=action,
                goal=goal,
                constraints=campaign.constraints,
                context={"hours_since_last_action": 24}
            )
            
            # Check if campaign ended
            is_last_day = i == len(metrics) - 2
            done = is_last_day or metrics_t1.get("status") == "completed"
            
            transition = Transition(
                state=state_t.to_tensor().numpy(),
                continuous_action=np.array([
                    action.get("bid_adjustment", 0),
                    action.get("budget_adjustment", 0)
                ]),
                discrete_action=np.array([
                    action.get("audience_action", 0),
                    action.get("creative_action", 0)
                ]),
                reward=reward_obj.total,
                next_state=state_t1.to_tensor().numpy(),
                done=done,
                campaign_id=campaign.campaign_id,
                timestamp=metrics_t.get("date", ""),
            )
            
            transitions.append(transition)
        
        return transitions
    
    def _extract_state(
        self,
        campaign: HistoricalCampaignData,
        metrics_history: List[Dict[str, Any]]
    ) -> CampaignState:
        """Extract state from metrics history"""
        current = metrics_history[-1]
        
        # Compute trends from history
        trends = self._compute_trends(metrics_history)
        
        # Get temporal features
        date_str = current.get("date", "")
        temporal = self._extract_temporal(date_str, campaign)
        
        # ML features (would come from separate prediction service)
        ml_features = {
            "audience_quality": current.get("audience_quality_score", 0.5),
            "creative_fatigue": current.get("creative_fatigue_score", 0),
            "predicted_cvr": current.get("predicted_cvr", current.get("cvr", 0.02)),
            "predicted_ltv": current.get("predicted_ltv", 0.5),
            "propensity": current.get("propensity_score", 0.5),
        }
        
        # Build state
        # Compute cumulative campaign spend up to this point
        total_campaign_spend = sum(m.get("spend", 0) for m in metrics_history)

        return CampaignState.from_campaign_metrics(
            campaign_id=campaign.campaign_id,
            metrics={
                **current,
                **trends,
                "goal_encoding": self._encode_goal(campaign.optimization_goal),
                "platform_encoding": self._encode_platform(campaign.platform),
                "budget_utilization": current.get("spend", 0) / max(current.get("daily_budget", 1000), 1),
                "daily_budget": current.get("daily_budget", 1000),
                "total_campaign_spend": total_campaign_spend,
            },
            temporal=temporal,
            ml_features=ml_features,
            normalization_params=self.normalization_params,
        )
    
    def _compute_trends(
        self,
        metrics_history: List[Dict[str, Any]],
        window: int = 7
    ) -> Dict[str, float]:
        """Compute metric trends over window"""
        if len(metrics_history) < 2:
            return {
                "ctr_trend_7d": 0,
                "cvr_trend_7d": 0,
                "roas_trend_7d": 0,
                "cpa_trend_7d": 0,
                "spend_trend_7d": 0,
            }
        
        recent = metrics_history[-min(window, len(metrics_history)):]
        
        def compute_trend(values: List[float]) -> float:
            if len(values) < 2:
                return 0
            # Simple linear trend
            x = np.arange(len(values))
            if np.std(values) > 0:
                slope = np.polyfit(x, values, 1)[0]
                return slope / (np.mean(values) + 1e-8)
            return 0
        
        return {
            "ctr_trend_7d": compute_trend([m.get("ctr", 0) for m in recent]),
            "cvr_trend_7d": compute_trend([m.get("cvr", 0) for m in recent]),
            "roas_trend_7d": compute_trend([m.get("roas", 0) for m in recent]),
            "cpa_trend_7d": compute_trend([m.get("cpa", 0) for m in recent]),
            "spend_trend_7d": compute_trend([m.get("spend", 0) for m in recent]),
        }
    
    def _extract_temporal(
        self,
        date_str: str,
        campaign: HistoricalCampaignData
    ) -> Dict[str, Any]:
        """Extract temporal features from date"""
        try:
            date = datetime.strptime(date_str[:10], "%Y-%m-%d")
        except (ValueError, TypeError):
            date = datetime.now()
        
        # Campaign age
        first_date_str = campaign.daily_metrics[0].get("date", date_str)[:10]
        try:
            first_date = datetime.strptime(first_date_str, "%Y-%m-%d")
            campaign_age = (date - first_date).days
        except (ValueError, TypeError):
            campaign_age = 0
        
        return {
            "hour": 12,  # Default to midday for daily data
            "day_of_week": date.weekday(),
            "day_of_month": date.day,
            "is_weekend": date.weekday() >= 5,
            "is_holiday": False,  # Would check holiday calendar
            "days_remaining": 30,  # Would compute from campaign end date
            "campaign_age_days": campaign_age,
        }
    
    def _infer_action(
        self,
        metrics_before: Dict[str, Any],
        metrics_after: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Infer action from state change"""
        # Infer bid adjustment from CPC change
        cpc_before = metrics_before.get("cpc", 1)
        cpc_after = metrics_after.get("cpc", 1)
        if cpc_before > 0:
            bid_change = (cpc_after - cpc_before) / cpc_before
        else:
            bid_change = 0
        
        # Infer budget adjustment from spend change
        spend_before = metrics_before.get("spend", 100)
        spend_after = metrics_after.get("spend", 100)
        budget_before = metrics_before.get("daily_budget", 1000)
        budget_after = metrics_after.get("daily_budget", 1000)
        
        if budget_before > 0:
            budget_change = (budget_after - budget_before) / budget_before
        else:
            budget_change = 0
        
        # Infer discrete actions (conservative defaults)
        audience_action = 0  # HOLD
        creative_action = 0  # HOLD
        
        return {
            "bid_adjustment": np.clip(bid_change, -0.5, 0.5),
            "budget_adjustment": np.clip(budget_change, -0.3, 0.3),
            "audience_action": audience_action,
            "creative_action": creative_action,
        }
    
    def _extract_action_from_log(self, action_log: Dict[str, Any]) -> Dict[str, Any]:
        """Extract action from logged action record"""
        return {
            "bid_adjustment": action_log.get("bid_change_pct", 0) / 100,
            "budget_adjustment": action_log.get("budget_change_pct", 0) / 100,
            "audience_action": action_log.get("audience_action_id", 0),
            "creative_action": action_log.get("creative_action_id", 0),
        }
    
    def _encode_goal(self, goal: str) -> float:
        """Encode optimization goal as float"""
        goal_map = {
            "roas": 0.0,
            "cpa": 0.25,
            "conversions": 0.5,
            "ctr": 0.75,
            "revenue": 1.0,
        }
        return goal_map.get(goal.lower(), 0.0)
    
    def _encode_platform(self, platform: str) -> float:
        """Encode platform as float"""
        platform_map = {
            "meta": 0.0,
            "google": 0.2,
            "tiktok": 0.4,
            "amazon": 0.6,
            "walmart": 0.8,
            "other": 1.0,
        }
        return platform_map.get(platform.lower(), 1.0)
    
    def compute_normalization_params(
        self,
        transitions: List[Transition]
    ) -> Dict[str, Tuple[float, float]]:
        """
        Compute normalization parameters from transitions
        
        Returns:
            Dictionary mapping feature names to (mean, std)
        """
        if not transitions:
            return {}
        
        states = np.stack([t.state for t in transitions])
        
        means = np.mean(states, axis=0)
        stds = np.std(states, axis=0)
        
        # Create named mapping (based on state vector order)
        feature_names = [
            "ctr", "cvr", "roas", "cpa", "cpc", "cpm",
            "spend_velocity", "impression_volume", "click_volume", "conversion_volume",
            "hour_of_day", "day_of_week", "day_of_month",
            "is_weekend", "is_holiday", "days_remaining",
            "ctr_trend_7d", "cvr_trend_7d", "roas_trend_7d",
            "cpa_trend_7d", "spend_trend_7d",
            "impression_share", "auction_pressure", "competitive_position",
            "audience_quality_score", "creative_fatigue_score",
            "predicted_cvr", "predicted_ltv", "propensity_score",
            "optimization_goal_encoding", "platform_encoding",
            "campaign_maturity", "budget_utilization",
            "log_daily_spend", "log_total_campaign_spend", "log_daily_budget",
        ]
        
        params = {}
        for i, name in enumerate(feature_names):
            if i < len(means):
                params[name] = (float(means[i]), float(stds[i]))
        
        return params


class OfflineTrainer:
    """
    [OfflineTrainer]
    Description: Runs offline SAC training on pre-built transitions with CQL regularization.
    Input: SACAgent, TrainingConfig, transitions (from OfflineDataExtractor.build_transitions).
    Output: Trained agent checkpoint -> used by load_sac_for_inference() / SafeDRLAgent.
    """
    
    def __init__(
        self,
        agent: SACAgent,
        training_config: TrainingConfig,
        reward_config: Optional[RewardConfig] = None
    ):
        """
        Args:
            agent: SAC agent to train
            training_config: Training configuration
            reward_config: Reward function configuration
        """
        self.agent = agent
        self.config = training_config
        self.reward_computer = RewardComputer(reward_config)
        
        self.replay_buffer = create_replay_buffer(
            capacity=training_config.replay_buffer_size,
            use_prioritized=training_config.use_per,
            alpha=training_config.per_alpha,
            beta_start=training_config.per_beta_start,
            beta_end=training_config.per_beta_end,
            beta_anneal_steps=training_config.per_beta_anneal_steps,
        )
        
        # Training metrics
        self.training_history = {
            "epoch": [],
            "actor_loss": [],
            "critic_loss": [],
            "alpha": [],
            "reward_mean": [],
            "validation_reward": [],
        }
    
    def load_transitions(self, transitions: List[Transition]):
        """
        [load_transitions]
        Description: Pushes transitions into replay buffer for training.
        Input: transitions from OfflineDataExtractor.build_transitions().
        Output: Populated replay buffer (internal); next: train().
        """
        # ----- INPUT LOGGING -----
        if _QA_IO_LOGGING:
            logger.info(f"[IO] INPUT: {len(transitions)} transitions into replay buffer")
            if transitions:
                logger.info(f"[IO] Sample: state shape={transitions[0].state.shape}, reward={transitions[0].reward:.4f}")
        logger.info(f"Loading {len(transitions)} transitions into replay buffer")
        
        for transition in tqdm(transitions, desc="Loading transitions"):
            self.replay_buffer.push(transition)
        
        # ----- OUTPUT LOGGING -----
        if _QA_IO_LOGGING:
            logger.info(f"[IO] OUTPUT: Replay buffer size={len(self.replay_buffer)} | Next: train()")
        logger.info(f"Replay buffer size: {len(self.replay_buffer)}")
    
    def train(
        self,
        num_epochs: int = 100,
        steps_per_epoch: int = 1000,
        validation_data: Optional[List[Transition]] = None,
        checkpoint_dir: Optional[str] = None,
        early_stopping: bool = True
    ) -> Dict[str, List[float]]:
        """
        Run offline training
        
        Args:
            num_epochs: Number of training epochs
            steps_per_epoch: Gradient steps per epoch
            validation_data: Optional validation transitions
            checkpoint_dir: Directory to save checkpoints
            early_stopping: Whether to use early stopping
            
        Returns:
            Training history dictionary
        """
        # ----- INPUT LOGGING -----
        if _QA_IO_LOGGING:
            logger.info(f"[IO] INPUT: num_epochs={num_epochs}, steps_per_epoch={steps_per_epoch}, checkpoint_dir={checkpoint_dir}")
            logger.info(f"[IO] Params: buffer_size={len(self.replay_buffer)}, min_buffer={self.config.min_buffer_size}")
        logger.info(f"Starting offline training: {num_epochs} epochs, {steps_per_epoch} steps/epoch")
        
        if len(self.replay_buffer) < self.config.min_buffer_size:
            raise ValueError(
                f"Insufficient data: {len(self.replay_buffer)} < {self.config.min_buffer_size}"
            )
        
        best_validation_reward = float("-inf")
        epochs_without_improvement = 0
        
        for epoch in range(num_epochs):
            epoch_metrics = self._train_epoch(steps_per_epoch)
            
            # Log metrics
            self.training_history["epoch"].append(epoch)
            self.training_history["actor_loss"].append(epoch_metrics["actor_loss"])
            self.training_history["critic_loss"].append(epoch_metrics["critic_loss"])
            self.training_history["alpha"].append(epoch_metrics["alpha"])
            self.training_history["reward_mean"].append(epoch_metrics["reward_mean"])
            
            # Validation
            if validation_data:
                val_reward = self._validate(validation_data)
                self.training_history["validation_reward"].append(val_reward)
                
                # Early stopping check
                if val_reward > best_validation_reward + self.config.early_stopping_min_delta:
                    best_validation_reward = val_reward
                    epochs_without_improvement = 0
                    
                    # Save best model
                    if checkpoint_dir:
                        self.agent.save(f"{checkpoint_dir}/best")
                else:
                    epochs_without_improvement += 1
                
                logger.info(
                    f"Epoch {epoch}: actor_loss={epoch_metrics['actor_loss']:.4f}, "
                    f"critic_loss={epoch_metrics['critic_loss']:.4f}, "
                    f"val_reward={val_reward:.4f}"
                )
                
                if early_stopping and epochs_without_improvement >= self.config.early_stopping_patience:
                    logger.info(f"Early stopping at epoch {epoch}")
                    break
            else:
                logger.info(
                    f"Epoch {epoch}: actor_loss={epoch_metrics['actor_loss']:.4f}, "
                    f"critic_loss={epoch_metrics['critic_loss']:.4f}"
                )
            
            # Checkpoint
            if checkpoint_dir and (epoch + 1) % 10 == 0:
                self.agent.save(f"{checkpoint_dir}/epoch_{epoch}")
        
        # Save final model
        if checkpoint_dir:
            self.agent.save(f"{checkpoint_dir}/final")
            # ----- OUTPUT LOGGING -----
            if _QA_IO_LOGGING:
                logger.info(f"[IO] OUTPUT: Checkpoint saved to {checkpoint_dir}/final | Next: load_sac_for_inference(), SafeDRLAgent")
        
        return self.training_history
    
    def _train_epoch(self, steps: int) -> Dict[str, float]:
        """Train for one epoch"""
        epoch_actor_loss = []
        epoch_critic_loss = []
        epoch_alpha = []
        
        for _ in range(steps):
            metrics = self.agent.update(self.replay_buffer)
            
            if metrics:
                epoch_actor_loss.append(metrics["actor_loss"])
                epoch_critic_loss.append(metrics["critic_loss"])
                epoch_alpha.append(metrics["alpha"])
        
        # Compute mean reward from recent transitions
        transitions, _, _ = self.replay_buffer.sample(min(1000, len(self.replay_buffer)))
        rewards = [t.reward for t in transitions]
        
        return {
            "actor_loss": np.mean(epoch_actor_loss) if epoch_actor_loss else 0,
            "critic_loss": np.mean(epoch_critic_loss) if epoch_critic_loss else 0,
            "alpha": np.mean(epoch_alpha) if epoch_alpha else self.agent.alpha,
            "reward_mean": np.mean(rewards),
        }
    
    def _validate(self, validation_data: List[Transition]) -> float:
        """Evaluate on validation data"""
        total_reward = 0
        
        for transition in validation_data:
            state = CampaignState.from_tensor(
                torch.tensor(transition.state, dtype=torch.float32)
            )
            
            # Get action from policy
            action = self.agent.select_action(state, deterministic=True)
            
            # Compare with actual reward (using logged reward as proxy)
            total_reward += transition.reward
        
        return total_reward / len(validation_data)
    
    def save_training_history(self, path: str):
        """Save training history to JSON"""
        with open(path, "w") as f:
            json.dump(self.training_history, f, indent=2)
        logger.info(f"Saved training history to {path}")
