"""
Cross-Platform X-Model — State, Action, Agent, and Inference (M5)

Implements the X-Model layer of the P & X Model HL Design:

  X-State:  Portfolio-level observation aggregating per-platform metrics,
            budget shares, trends, and constraint signals.

  X-Action: Continuous budget allocation weights across platforms.
            The X-Model outputs a softmax-normalized weight vector that
            determines how total portfolio budget is distributed.

  XModelAgent:  A dedicated SAC agent operating on the X-Model MDP.

  M5 (X-Execution): Given a portfolio snapshot, the X-Model selects
            allocation weights, then delegates to per-platform P-Models
            (M2) for campaign-level actions.

Architecture reference:
  M4 — X-Training:  Train XModelAgent on portfolio-level transitions
        generated by M3 (x_training_data.py).
  M5 — X-Execution:  XModelAgent.select_allocation() → calls P-Execution
        per platform → returns combined cross-platform result.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from .config import DRLConfig, TrainingConfig

logger = logging.getLogger(__name__)


# The 5 platforms the X-Model allocates budget across.
X_PLATFORMS: List[str] = ["meta", "google", "tiktok", "amazon", "walmart"]
NUM_PLATFORMS = len(X_PLATFORMS)

# Per-platform feature count in the X-State vector.
# Each platform contributes:  roas, cpa_inv, ctr, cvr, marginal_roas,
# spend_share, spend_trend_7d, roas_trend_7d, conversion_trend_7d,
# num_campaigns_norm, segment_count_norm, top_segment_roas, avg_frequency_ratio
FEATURES_PER_PLATFORM = 13

# Global portfolio features appended after per-platform features.
# portfolio_roas, total_budget_log, budget_utilization,
# portfolio_hhi (concentration), num_active_platforms / NUM_PLATFORMS
GLOBAL_FEATURES = 5

X_STATE_DIM = NUM_PLATFORMS * FEATURES_PER_PLATFORM + GLOBAL_FEATURES  # 70

# X-Action dimension = one continuous weight per platform
X_ACTION_DIM = NUM_PLATFORMS  # 5


# ---------------------------------------------------------------------------
# X-State dataclass
# ---------------------------------------------------------------------------

@dataclass
class XModelState:
    """
    Portfolio-level state for the X-Model.

    Built from a PlatformPortfolio snapshot.  The state vector is ordered
    as: [platform_0_features, ..., platform_N_features, global_features].
    """

    # Per-platform feature blocks (ordered by X_PLATFORMS)
    platform_features: Dict[str, Dict[str, float]] = field(default_factory=dict)

    # Global portfolio features
    portfolio_roas: float = 0.0
    total_budget_log: float = 0.0         # log1p(total_budget) / log1p(1e6)
    budget_utilization: float = 0.0
    portfolio_hhi: float = 0.0            # Herfindahl–Hirschman index (concentration)
    active_platform_ratio: float = 0.0    # num_active / NUM_PLATFORMS

    def to_tensor(self, device: str = "cpu") -> torch.Tensor:
        """Convert to a flat tensor of shape (X_STATE_DIM,)."""
        vec: List[float] = []

        for platform in X_PLATFORMS:
            pf = self.platform_features.get(platform, {})
            vec.extend([
                pf.get("roas", 0.0),
                pf.get("cpa_inv", 0.0),       # 1/cpa, higher = better
                pf.get("ctr", 0.0),
                pf.get("cvr", 0.0),
                pf.get("marginal_roas", 0.0),
                pf.get("spend_share", 0.0),
                pf.get("spend_trend_7d", 0.0),
                pf.get("roas_trend_7d", 0.0),
                pf.get("conversion_trend_7d", 0.0),
                pf.get("num_campaigns_norm", 0.0),
                # Audience segment features
                pf.get("segment_count_norm", 0.0),
                pf.get("top_segment_roas", 0.0),
                pf.get("avg_frequency_ratio", 0.0),
            ])

        vec.extend([
            self.portfolio_roas,
            self.total_budget_log,
            self.budget_utilization,
            self.portfolio_hhi,
            self.active_platform_ratio,
        ])

        return torch.tensor(vec, dtype=torch.float32, device=device)

    @classmethod
    def state_dim(cls) -> int:
        return X_STATE_DIM

    def to_dict(self) -> Dict[str, Any]:
        return {
            "platform_features": self.platform_features,
            "portfolio_roas": self.portfolio_roas,
            "total_budget_log": self.total_budget_log,
            "budget_utilization": self.budget_utilization,
            "portfolio_hhi": self.portfolio_hhi,
            "active_platform_ratio": self.active_platform_ratio,
        }


@dataclass
class XModelAction:
    """
    X-Model action: budget allocation weights across platforms.

    The raw network output is in (-1, 1) per platform; softmax converts
    these to a valid probability simplex (allocation shares summing to 1).
    """

    # Allocation shares per platform (sum to 1.0)
    allocation_weights: Dict[str, float] = field(default_factory=dict)

    # Metadata
    confidence: float = 0.0
    entropy: float = 0.0
    q_value: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "allocation_weights": self.allocation_weights,
            "confidence": self.confidence,
            "entropy": self.entropy,
            "q_value": self.q_value,
        }


# ---------------------------------------------------------------------------
# X-Model network (lightweight actor-critic for allocation)
# ---------------------------------------------------------------------------

class XModelActor(nn.Module):
    """
    Actor for the X-Model.

    Outputs raw logits for each platform.  During execution, these are
    converted to allocation weights via constrained softmax.
    """

    def __init__(self, state_dim: int = X_STATE_DIM, action_dim: int = X_ACTION_DIM):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(state_dim, 256),
            nn.LayerNorm(256),
            nn.ReLU(),
            nn.Linear(256, 256),
            nn.LayerNorm(256),
            nn.ReLU(),
            nn.Linear(256, 128),
            nn.LayerNorm(128),
            nn.ReLU(),
        )
        self.mean_head = nn.Linear(128, action_dim)
        self.log_std_head = nn.Linear(128, action_dim)

        # Clamp log-std for stability
        self.LOG_STD_MIN = -5.0
        self.LOG_STD_MAX = 2.0

    def forward(self, state: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        h = self.net(state)
        mean = self.mean_head(h)
        log_std = self.log_std_head(h).clamp(self.LOG_STD_MIN, self.LOG_STD_MAX)
        return mean, log_std

    def sample(
        self, state: torch.Tensor, deterministic: bool = False
    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        Sample allocation logits from the policy.

        Returns:
            (allocation_weights, log_prob, entropy)

            allocation_weights: (B, NUM_PLATFORMS) — softmax-normalized.
        """
        mean, log_std = self.forward(state)
        std = log_std.exp()

        if deterministic:
            raw = mean
        else:
            dist = torch.distributions.Normal(mean, std)
            raw = dist.rsample()

        # Convert to allocation weights via softmax
        weights = F.softmax(raw, dim=-1)

        # Log-prob in the original Gaussian space (for SAC entropy objective)
        if deterministic:
            log_prob = torch.zeros(state.shape[0], device=state.device)
            entropy = torch.zeros(state.shape[0], device=state.device)
        else:
            dist = torch.distributions.Normal(mean, std)
            log_prob = dist.log_prob(raw).sum(dim=-1)
            entropy = dist.entropy().sum(dim=-1)

        return weights, log_prob, entropy


class XModelCritic(nn.Module):
    """Twin Q-networks for the X-Model."""

    def __init__(self, state_dim: int = X_STATE_DIM, action_dim: int = X_ACTION_DIM):
        super().__init__()

        input_dim = state_dim + action_dim

        self.q1 = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.LayerNorm(256),
            nn.ReLU(),
            nn.Linear(256, 256),
            nn.LayerNorm(256),
            nn.ReLU(),
            nn.Linear(256, 1),
        )

        self.q2 = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.LayerNorm(256),
            nn.ReLU(),
            nn.Linear(256, 256),
            nn.LayerNorm(256),
            nn.ReLU(),
            nn.Linear(256, 1),
        )

    def forward(
        self, state: torch.Tensor, action: torch.Tensor
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        x = torch.cat([state, action], dim=-1)
        return self.q1(x).squeeze(-1), self.q2(x).squeeze(-1)


# ---------------------------------------------------------------------------
# XModelAgent — SAC-based cross-platform allocation agent
# ---------------------------------------------------------------------------

class XModelAgent:
    """
    Dedicated SAC agent for cross-platform budget allocation (X-Model).

    Smaller and simpler than the per-campaign SACAgent because the X-Model
    MDP has:
      - Continuous-only action space (allocation weights, no discrete heads)
      - Lower-dimensional state (55 vs 42 per campaign)
      - Fewer transitions (one per rebalance cycle, not per campaign)
    """

    def __init__(
        self,
        state_dim: int = X_STATE_DIM,
        action_dim: int = X_ACTION_DIM,
        gamma: float = 0.99,
        tau: float = 0.005,
        alpha: float = 0.2,
        actor_lr: float = 3e-4,
        critic_lr: float = 3e-4,
        device: str = "cpu",
    ):
        self.state_dim = state_dim
        self.action_dim = action_dim
        self.gamma = gamma
        self.tau = tau
        self.alpha = alpha
        self.device = device

        # Networks
        self.actor = XModelActor(state_dim, action_dim).to(device)
        self.critic = XModelCritic(state_dim, action_dim).to(device)
        self.critic_target = XModelCritic(state_dim, action_dim).to(device)
        self.critic_target.load_state_dict(self.critic.state_dict())
        for p in self.critic_target.parameters():
            p.requires_grad = False

        # Optimizers
        self.actor_optimizer = optim.Adam(self.actor.parameters(), lr=actor_lr)
        self.critic_optimizer = optim.Adam(self.critic.parameters(), lr=critic_lr)

        self.total_steps = 0

    # ------------------------------------------------------------------
    # Inference (M5)
    # ------------------------------------------------------------------

    def select_allocation(
        self,
        x_state: XModelState,
        deterministic: bool = True,
        min_share: float = 0.05,
        max_share: float = 0.80,
    ) -> XModelAction:
        """
        M5 entry-point: select cross-platform allocation weights.

        The raw softmax output is clamped to [min_share, max_share] per
        platform, then re-normalized to sum to 1.
        """
        with torch.no_grad():
            state_tensor = x_state.to_tensor(self.device).unsqueeze(0)
            weights, _log_prob, entropy = self.actor.sample(
                state_tensor, deterministic=deterministic
            )

            # Q-value estimate
            q1, q2 = self.critic(state_tensor, weights)
            q_value = torch.min(q1, q2).item()

            weights_np = weights[0].cpu().numpy()

        # Apply min/max share constraints and re-normalize
        weights_np = np.clip(weights_np, min_share, max_share)
        weights_np = weights_np / weights_np.sum()

        allocation = {
            platform: float(weights_np[i])
            for i, platform in enumerate(X_PLATFORMS)
        }

        max_entropy = np.log(NUM_PLATFORMS)
        confidence = 1.0 - (entropy.item() / max_entropy) if max_entropy > 0 else 0.5
        confidence = float(np.clip(confidence, 0.0, 1.0))

        return XModelAction(
            allocation_weights=allocation,
            confidence=confidence,
            entropy=entropy.item(),
            q_value=q_value,
        )

    # ------------------------------------------------------------------
    # Training (M4 uses these)
    # ------------------------------------------------------------------

    def update(
        self,
        states: torch.Tensor,
        actions: torch.Tensor,
        rewards: torch.Tensor,
        next_states: torch.Tensor,
        dones: torch.Tensor,
    ) -> Dict[str, float]:
        """
        One SAC gradient step on a batch of X-Model transitions.

        Args:
            states:      (B, X_STATE_DIM)
            actions:     (B, X_ACTION_DIM) — allocation weights
            rewards:     (B,)
            next_states: (B, X_STATE_DIM)
            dones:       (B,)

        Returns:
            Dict of training metrics.
        """
        # --- Critic update ---
        with torch.no_grad():
            next_weights, next_log_prob, _ = self.actor.sample(next_states)
            next_q1, next_q2 = self.critic_target(next_states, next_weights)
            next_q = torch.min(next_q1, next_q2) - self.alpha * next_log_prob
            target_q = rewards + (1.0 - dones) * self.gamma * next_q

        q1, q2 = self.critic(states, actions)
        critic_loss = F.mse_loss(q1, target_q) + F.mse_loss(q2, target_q)

        self.critic_optimizer.zero_grad()
        critic_loss.backward()
        nn.utils.clip_grad_norm_(self.critic.parameters(), 1.0)
        self.critic_optimizer.step()

        # --- Actor update ---
        new_weights, log_prob, entropy = self.actor.sample(states)
        q1_new, q2_new = self.critic(states, new_weights)
        min_q = torch.min(q1_new, q2_new)
        actor_loss = (self.alpha * log_prob - min_q).mean()

        self.actor_optimizer.zero_grad()
        actor_loss.backward()
        nn.utils.clip_grad_norm_(self.actor.parameters(), 1.0)
        self.actor_optimizer.step()

        # --- Soft target update ---
        for tp, p in zip(self.critic_target.parameters(), self.critic.parameters()):
            tp.data.copy_(self.tau * p.data + (1.0 - self.tau) * tp.data)

        self.total_steps += 1

        return {
            "x_critic_loss": critic_loss.item(),
            "x_actor_loss": actor_loss.item(),
            "x_entropy": entropy.mean().item(),
            "x_q_value": min_q.mean().item(),
        }

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def save(self, path: str) -> None:
        path = Path(path)
        path.mkdir(parents=True, exist_ok=True)

        torch.save({
            "actor_state_dict": self.actor.state_dict(),
            "critic_state_dict": self.critic.state_dict(),
            "critic_target_state_dict": self.critic_target.state_dict(),
            "actor_optimizer_state_dict": self.actor_optimizer.state_dict(),
            "critic_optimizer_state_dict": self.critic_optimizer.state_dict(),
            "total_steps": self.total_steps,
            "state_dim": self.state_dim,
            "action_dim": self.action_dim,
            "alpha": self.alpha,
            "gamma": self.gamma,
            "tau": self.tau,
        }, path / "x_model.pt")

        logger.info(f"Saved X-Model to {path}")

    def load(self, path: str) -> None:
        path = Path(path)
        ckpt_file = path / "x_model.pt"

        try:
            ckpt = torch.load(ckpt_file, map_location=self.device, weights_only=False)
        except TypeError:
            ckpt = torch.load(ckpt_file, map_location=self.device)

        self.actor.load_state_dict(ckpt["actor_state_dict"])
        self.critic.load_state_dict(ckpt["critic_state_dict"])
        self.critic_target.load_state_dict(ckpt["critic_target_state_dict"])
        self.actor_optimizer.load_state_dict(ckpt["actor_optimizer_state_dict"])
        self.critic_optimizer.load_state_dict(ckpt["critic_optimizer_state_dict"])
        self.total_steps = ckpt.get("total_steps", 0)
        self.alpha = ckpt.get("alpha", self.alpha)

        logger.info(f"Loaded X-Model from {path} (steps={self.total_steps})")

    # ------------------------------------------------------------------
    # Diagnostics
    # ------------------------------------------------------------------

    def get_diagnostics(self) -> Dict[str, Any]:
        return {
            "total_steps": self.total_steps,
            "state_dim": self.state_dim,
            "action_dim": self.action_dim,
            "alpha": self.alpha,
            "gamma": self.gamma,
        }


# ---------------------------------------------------------------------------
# Helper: build XModelState from PlatformPortfolio
# ---------------------------------------------------------------------------

def build_x_state(
    portfolio_dict: Dict[str, Any],
    total_budget: float,
) -> XModelState:
    """
    Convert a portfolio dict (from PlatformPortfolio.to_dict() or raw
    aggregated metrics) into an XModelState.

    Expected keys in *portfolio_dict*:
        platforms: Dict[str, {roas, cpa, ctr, cvr, marginal_roas,
                              current_budget_share, spend_trend_7d,
                              roas_trend_7d, conversion_trend_7d,
                              num_campaigns,
                              segment_count, top_segment_roas,
                              avg_frequency, max_frequency}]
        portfolio_roas: float
    """
    platforms_data = portfolio_dict.get("platforms", {})

    platform_features: Dict[str, Dict[str, float]] = {}
    shares = []

    for platform in X_PLATFORMS:
        pm = platforms_data.get(platform, {})
        cpa = pm.get("cpa", 0.0)
        share = pm.get("current_budget_share", 0.0)
        shares.append(share)

        # Audience segment features
        seg_count = pm.get("segment_count", 0)
        top_seg_roas = pm.get("top_segment_roas", 0.0)
        avg_freq = pm.get("avg_frequency", 0.0)
        max_freq = pm.get("max_frequency", 1.0)

        platform_features[platform] = {
            "roas": min(pm.get("roas", 0.0) / 5.0, 1.0),  # normalize to ~[0,1]
            "cpa_inv": 1.0 / max(cpa, 1.0) if cpa > 0 else 0.0,
            "ctr": min(pm.get("ctr", 0.0), 1.0),
            "cvr": min(pm.get("cvr", 0.0), 1.0),
            "marginal_roas": min(pm.get("marginal_roas", 0.0) / 5.0, 1.0),
            "spend_share": share,
            "spend_trend_7d": np.clip(pm.get("spend_trend_7d", 0.0), -1.0, 1.0),
            "roas_trend_7d": np.clip(pm.get("roas_trend_7d", 0.0), -1.0, 1.0),
            "conversion_trend_7d": np.clip(pm.get("conversion_trend_7d", 0.0), -1.0, 1.0),
            "num_campaigns_norm": min(pm.get("num_campaigns", 0) / 20.0, 1.0),
            # Audience segment features
            "segment_count_norm": min(seg_count / 10.0, 1.0),
            "top_segment_roas": min(top_seg_roas / 5.0, 1.0),
            "avg_frequency_ratio": min(avg_freq / max(max_freq, 1.0), 1.0),
        }

    # Global features
    shares_arr = np.array(shares)
    hhi = float(np.sum(shares_arr ** 2)) if shares_arr.sum() > 0 else 0.0
    num_active = sum(1 for s in shares if s > 0.01)
    total_spend = sum(
        platforms_data.get(p, {}).get("total_spend", 0.0) for p in X_PLATFORMS
    )

    return XModelState(
        platform_features=platform_features,
        portfolio_roas=min(portfolio_dict.get("portfolio_roas", 0.0) / 5.0, 1.0),
        total_budget_log=float(np.log1p(total_budget) / np.log1p(1e6)),
        budget_utilization=min(total_spend / max(total_budget, 1.0), 1.0),
        portfolio_hhi=hhi,
        active_platform_ratio=num_active / NUM_PLATFORMS,
    )
